<?php
/**
 * Copyright 2016 Betaout Analytics
 *
 * This file is part of Betaout_Analytics.
 *
 * Betaout_Analytics is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Betaout_Analytics is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Betaout_Analytics.  If not, see <http://www.gnu.org/licenses/>.
 */

?>
<?php /* @var $block \Betaout\Analytics\Block\Betaout */ ?>
<?php
$om = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $om->get('Magento\Customer\Model\Session');
?>
 <script type="text/javascript">
            var _bout = _bout || [];
            var _boutAKEY ='<?php echo $block->escapeJsQuote($block->getApiKey()); ?>';
            var _boutPID = '<?php echo $block->escapeJsQuote($block->getProjectId()); ?>';
            var d = document, f = d.getElementsByTagName("script")[0], _sc = d.createElement("script");
            _sc.type = "text/javascript";
            _sc.async = true;
            _sc.src = "//d22vyp49cxb9py.cloudfront.net/jal-v2.min.js";
            f.parentNode.insertBefore(_sc, f);
             <?php 
             $product=$block->getCurrentProduct();
              $cats = $product->getCategoryIds();
             ?>
            _bout.push(["identify", {"customer_id":"<?php echo $customerSession->getCustomer()->getId()?>","email":"<?php echo $customerSession->getCustomer()->getEmail()?>"},{productId:"<?php echo $product->getId()?>",categoryId:"<?php echo $cats[0]?>",brandName:""} ]);
      
</script>
